--- Makefile_orig	2021-10-06 09:20:27.417894652 +0200
+++ Makefile_new	2021-10-06 09:23:14.240379084 +0200
@@ -133,6 +133,7 @@
 $(GLOG_LIB): $(GLOG_SRC)
 	tar zxf $< -C $(THIRD_PARTY_SRC)
 	cd $(basename $(basename $(THIRD_PARTY_SRC)/$(notdir $<))); \
+	patch src/demangle.cc ../../../demangle_strings.patch
 	./configure --prefix=$(THIRD_PARTY); \
 	make install
 
